spring:
  application:
    name: config-client
  output:
    ansi:
      enabled: always
  cloud:
    config:
       name: config-client
       profile: dev
       failFast: true
       label: master


server:
  port: 9090

foo1: "{cipher}AQASAj3S7DkjrhlRA1CcnthPOkEW8wJQees1qm0/iBYmJGp7fDfP1P3WeLSnMOg5w1Ln1VyNiaf9000GpNCLIYjbwyPSpWQ+Gf4HnkXNKEGVkN5e8r+TSizl+OdH2jdhCw3tQEDCDo6yYpI2Ozdwi0A8X6XvWBQtDKEqBTVnRMvWWlft89UTDSsGjdr+ZP/ZAee3NPJUoSdNwlJGhxlbJrlrbBeNu9HaZ5kSpZ6olmRZR5X+DChDk8j71sarAwFrbUKzzMdbWRKLyy+RnpPE0SSFWIxDd3WArGajAGgG3m5dTeHl2ovT0jZTqYHv1mcRhGJzA6d6pGxaRGuVeC2vPchKjdLAPcr42wS6DAJ6U81nAgDKU+SxAbBJQqi1SAqbS4I="
