DROP TABLE IF EXISTS `template`;
CREATE TABLE `template` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(36) DEFAULT NULL,
  `createTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `template_0`;
CREATE TABLE `template_0` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(36) DEFAULT NULL,
  `createTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `template_1`;
CREATE TABLE `template_1` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(36) DEFAULT NULL,
  `createTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `template_2`;
CREATE TABLE `template_2` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(36) DEFAULT NULL,
  `createTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `template_3`;
CREATE TABLE `template_3` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(36) DEFAULT NULL,
  `createTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `template_4`;
CREATE TABLE `template_4` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(36) DEFAULT NULL,
  `createTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `template_5`;
CREATE TABLE `template_5` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(36) DEFAULT NULL,
  `createTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `template_6`;
CREATE TABLE `template_6` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(36) DEFAULT NULL,
  `createTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `template_7`;
CREATE TABLE `template_7` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(36) DEFAULT NULL,
  `createTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `template_8`;
CREATE TABLE `template_8` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(36) DEFAULT NULL,
  `createTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `template_9`;
CREATE TABLE `template_9` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(36) DEFAULT NULL,
  `createTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `template_10`;
CREATE TABLE `template_10` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(36) DEFAULT NULL,
  `createTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `template_11`;
CREATE TABLE `template_11` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(36) DEFAULT NULL,
  `createTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `template_12`;
CREATE TABLE `template_12` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(36) DEFAULT NULL,
  `createTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `template_13`;
CREATE TABLE `template_13` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(36) DEFAULT NULL,
  `createTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `template_14`;
CREATE TABLE `template_14` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(36) DEFAULT NULL,
  `createTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `template_15`;
CREATE TABLE `template_15` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(36) DEFAULT NULL,
  `createTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


